# SwiftLint Configuration for MacCleaner (Lustra)
# Enterprise-grade linting rules

disabled_rules:
  - trailing_whitespace
  - line_length
  - todo
  - nesting

opt_in_rules:
  - empty_count
  - empty_string
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - MacCleaner

excluded:
  - MacCleanerTests
  - Pods
  - DerivedData
  - .build

# Rule configurations
force_cast: warning
force_try: warning
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - i
    - x
    - y
    - to

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"
